title: Welcome to GitHub pages
author: EstebanMH
email: Emarentes@humboldt.org.co
description: > # this means to ignore newlines until "baseurl:"
 Genereal description in how to use GitHub for create pages, with the editor Jekyll

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
